/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

import Controladores.CoordinadorFrames;
import dtos.ClienteDTO;
import java.util.List;
/**
 *
 * @author aaron
 */
public class pnlBuscador extends javax.swing.JPanel {

    private CoordinadorFrames coordinadorF;
    /**
     * Creates new form pnlBuscador
     */
    public pnlBuscador(CoordinadorFrames coordinadorF) {
        this.coordinadorF = coordinadorF;
        initComponents();
        tablaBusqueda.setDefaultEditor(Object.class, null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        entradaFiltro = new javax.swing.JTextField();
        FiltroClientes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBusqueda = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel de busqueda de clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 12))); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(836, 533));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Buscar clientes:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 26, 100, -1));

        entradaFiltro.setColumns(20);
        entradaFiltro.setMaximumSize(new java.awt.Dimension(25, 25));
        entradaFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaFiltroActionPerformed(evt);
            }
        });
        entradaFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                entradaFiltroKeyReleased(evt);
            }
        });
        add(entradaFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 23, -1, -1));

        FiltroClientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        FiltroClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nombre", "Correo", "Numero" }));
        FiltroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroClientesActionPerformed(evt);
            }
        });
        add(FiltroClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 23, -1, -1));

        tablaBusqueda.setBackground(new java.awt.Color(255, 252, 249));
        tablaBusqueda.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        tablaBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellido paterno", "Apellido Materno", "Telefono", "Correo", "Puntos de fidelidad"
            }
        ));
        tablaBusqueda.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tablaBusqueda.setMinimumSize(new java.awt.Dimension(836, 536));
        tablaBusqueda.setPreferredSize(new java.awt.Dimension(836, 536));
        tablaBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBusquedaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaBusqueda);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 50, 830, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void FiltroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltroClientesActionPerformed

    private void entradaFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaFiltroActionPerformed

    private void entradaFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entradaFiltroKeyReleased
      

        // 2. Lo que el usuario escribió
        String textofiltro = entradaFiltro.getText().toLowerCase().trim();
        //2.1 
        String tipoFiltro = FiltroClientes.getSelectedItem().toString();
        
         // 3 pedir lista
         List<ClienteDTO> resultados = coordinadorF.solicitarBusqueda(textofiltro, tipoFiltro);
       
        llenarTabla(resultados);
    }//GEN-LAST:event_entradaFiltroKeyReleased

    private void llenarTabla(List<ClienteDTO> lista) {
        // 1. Obtenemos el modelo de la tabla que creó NetBeans
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaBusqueda.getModel();

        // 2. Limpiamos todas las filas existentes (incluyendo los datos dummy)
        modelo.setRowCount(0);

        // 3. Si la lista no es nula, recorremos y agregamos
        if (lista != null) {
            for (ClienteDTO cliente : lista) {
                Object[] fila = {
                    cliente.getNombres(),
                    cliente.getApellidoPaterno(),
                    cliente.getApellidoMaterno(),
                    cliente.getTelefono(),
                    cliente.getCorreo(),
                    cliente.getPuntos() // O el dato que quieras mostrar al final
                };
                modelo.addRow(fila);
            }
        }
    }
    private void tablaBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBusquedaMouseClicked
        if(evt.getClickCount() == 2){
            // para seleccionar una fila entera
            int fila = tablaBusqueda.getSelectedRow();
            if(fila != -1){
               
                // PENDIENTE HASTA CONECTAR LA LOGICA CON LA PRESENTACION
                coordinadorF.mostrarGestionCliente();
                
            }
        }
    }//GEN-LAST:event_tablaBusquedaMouseClicked
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FiltroClientes;
    private javax.swing.JTextField entradaFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaBusqueda;
    // End of variables declaration//GEN-END:variables
}
