/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

import Controladores.CoordinadorFrames;
import java.awt.Color;

/**
 *
 * @author aaron
 */
public class PnlBuscadorIngrediente extends javax.swing.JPanel {

    private CoordinadorFrames coordinadorFrames;
    
    // texto del textfield
    private final String TEXTOBUSCADOR = "Introduce texto...";
    
    /**
     * Creates new form pnlBuscadorIngrediente
     */
    public PnlBuscadorIngrediente(CoordinadorFrames coordinadorF) {
        this.coordinadorFrames = coordinadorF;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoBusqueda = new javax.swing.JTextField();
        ComboboxFiltros = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIngredientes = new javax.swing.JTable();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscador de ingredientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 12)), "sa"), "Panel busqueda de ingredientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 12))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Buscar ingrediente:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, -1));

        campoBusqueda.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoBusqueda.setForeground(new java.awt.Color(153, 153, 153));
        campoBusqueda.setText("Introduce texto...");
        campoBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoBusquedaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoBusquedaFocusLost(evt);
            }
        });
        campoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBusquedaActionPerformed(evt);
            }
        });
        add(campoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 210, -1));

        ComboboxFiltros.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ComboboxFiltros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Unidad de medida", "Nombre" }));
        ComboboxFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboboxFiltrosActionPerformed(evt);
            }
        });
        add(ComboboxFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, 20));

        tablaIngredientes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Unidad de medida", "Stock", "Estado", "Imagen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaIngredientes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 790, 420));
        add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));
        add(filler4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));
        add(filler5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));
        add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));
        add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void campoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBusquedaActionPerformed

    private void campoBusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoBusquedaFocusLost
        if(campoBusqueda.getText().isEmpty() || campoBusqueda.getText().isBlank()){
            campoBusqueda.setText(TEXTOBUSCADOR);
            campoBusqueda.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_campoBusquedaFocusLost

    private void campoBusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoBusquedaFocusGained
        if(campoBusqueda.getText().equals(TEXTOBUSCADOR)){
            campoBusqueda.setText("");
            campoBusqueda.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_campoBusquedaFocusGained

    private void ComboboxFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboboxFiltrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboboxFiltrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboboxFiltros;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaIngredientes;
    // End of variables declaration//GEN-END:variables
}
