/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

/**
 *
 * @author aaron
 */
public class pnlBuscador extends javax.swing.JPanel {

    /**
     * Creates new form pnlBuscador
     */
    public pnlBuscador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        entradaFiltro = new javax.swing.JTextField();
        FiltroClientes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBusqueda = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel de busqueda de clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(836, 533));

        jLabel1.setText("Buscar clientes:");
        add(jLabel1);

        entradaFiltro.setColumns(20);
        entradaFiltro.setMaximumSize(new java.awt.Dimension(25, 25));
        entradaFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaFiltroActionPerformed(evt);
            }
        });
        add(entradaFiltro);

        FiltroClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nombre", "Correo", "Numero" }));
        FiltroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroClientesActionPerformed(evt);
            }
        });
        add(FiltroClientes);

        tablaBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellido paterno", "Apellido Materno", "Telefono", "Correo", "Puntos de fidelidad"
            }
        ));
        tablaBusqueda.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tablaBusqueda.setMinimumSize(new java.awt.Dimension(836, 536));
        tablaBusqueda.setPreferredSize(new java.awt.Dimension(836, 536));
        jScrollPane1.setViewportView(tablaBusqueda);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void FiltroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltroClientesActionPerformed

    private void entradaFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaFiltroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FiltroClientes;
    private javax.swing.JTextField entradaFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaBusqueda;
    // End of variables declaration//GEN-END:variables
}
