/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

import Controladores.CoordinadorFrames;
import dtos.ClienteDTO;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
 
/**
 *
 * @author aaron
 */
public class pnlClienteFrecuente extends javax.swing.JPanel {
    private CoordinadorFrames coordinadorF;
    private FrmEdicionClienteFrecuente xd;
    /**
     * Creates new form pnlClienteFrecuente
     */
    public pnlClienteFrecuente(CoordinadorFrames coordinadorF) {
        this.coordinadorF = coordinadorF;
        initComponents();
        pnlBuscador bs = new pnlBuscador(this.coordinadorF);
        bs.setSize(736,433);
        bs.setLocation(0,0);
        content.removeAll();
        content.add(bs, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regresarMenuBoton = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        registrarClienteBoton = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setMaximumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(800, 478));
        setLayout(new java.awt.BorderLayout());

        regresarMenuBoton.setText("Volver al menu");
        regresarMenuBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarMenuBotonActionPerformed(evt);
            }
        });

        content.setForeground(new java.awt.Color(255, 252, 249));
        content.setLayout(new java.awt.BorderLayout());

        registrarClienteBoton.setText("RegistrarCliente");
        registrarClienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarClienteBotonActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar Cliente");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarClienteBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regresarMenuBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarMenuBoton)
                    .addComponent(registrarClienteBoton)
                    .addComponent(eliminar))
                .addGap(35, 35, 35))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void registrarClienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarClienteBotonActionPerformed
      coordinadorF.mostrarRegistroCliente();
      
        ClienteDTO clienteExtraido = xd.getClienteActual();
        if (clienteExtraido != null) {
            //peridr al coordinador que lo mande a la base de datos
            coordinadorF.mostrarRegistro(clienteExtraido);
        }
        // cliente guardado
        JOptionPane.showMessageDialog(this, "Cliente guardado con éxito");
    }//GEN-LAST:event_registrarClienteBotonActionPerformed

    private void regresarMenuBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarMenuBotonActionPerformed
       coordinadorF.rergesarAlMenu();
    }//GEN-LAST:event_regresarMenuBotonActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JButton eliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registrarClienteBoton;
    private javax.swing.JButton regresarMenuBoton;
    // End of variables declaration//GEN-END:variables
}
