/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

import Controladores.CoordinadorFrames;
import java.awt.BorderLayout;
import javax.swing.JButton;
import utilerias.BotonUtileria;

/**
 *
 * @author aaron
 */
public class PnlIngredientes extends javax.swing.JPanel {
    
    private CoordinadorFrames coordinadorFrames;
    
    private final int xSize = 736;
    private final int ySize = 433;
    /**
     * Creates new form pnlIngredientes
     */
    public PnlIngredientes(CoordinadorFrames coordinadorF) {
        this.coordinadorFrames = coordinadorF;
        initComponents();
        PnlBuscadorIngrediente buscadorIngrediente = new PnlBuscadorIngrediente(this.coordinadorFrames);
        this.add(buscadorIngrediente, BorderLayout.CENTER);
        // configurar el buscador
        buscadorIngrediente.setSize(xSize, ySize);
        
        // agregar botones creacion
        JButton btnEliminar = BotonUtileria.botonUtileriaGenérico("Eliminar");
        JButton btnRegistrar = BotonUtileria.botonUtileriaGenérico("Registrar ingrediente");
        JButton btnVolverMenu = BotonUtileria.botonUtileriaGenérico("Regresar al menu");
        
        // agregar acciones para estilizarlo más
        btnEliminar.addActionListener(e->{});
        btnRegistrar.addActionListener(e->{});
        
        
        btnVolverMenu.addActionListener(e ->{coordinadorF.rergesarAlMenu();});
        
        // agregar al panel 1
        jPanel1.add(btnEliminar);
        jPanel1.add(btnRegistrar);
        jPanel1.add(btnVolverMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());
        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
